<div style="background-color:#eaf2ff; padding:16px; border-left:6px solid #2563eb; border-radius:6px;">
<h1 style="margin:0; color:#1e3a8a;"> Retail Dataset Cleaning - George Warlow</h1>
<p style="margin-bottom:0;">Python & Pandas Data Quality Project</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Table 1: Categories</h3>
</div>

In [1]:
import pandas as pd

In [2]:
categories_df = pd.read_csv("challenge_02_data/categories.csv")

categories_df

   category_id        name
0            1     Cat-One
1            2  category_2
2            3  Category_3
3            4  Category_4
4            5  Category_5

<div style="background-color:#f3e8ff; padding:12px; border-left:5px solid #8b5cf6; border-radius:6px;">
<h3 style="margin:0;">Thoughts</h3>
<p style="margin-bottom:0;">

Dataset is small enough to identify problems by eye.

Category column follows a pattern and can be systematically generated.

</p>
</div>

<div style="background-color:#fdecec; padding:12px; border-left:5px solid #dc2626; border-radius:6px;">
<h3 style="margin:0;">Data Quality Issue</h3>
<p style="margin-bottom:0;">Problems Identified: 

1. Category 1 is named in a different format to the rest of the categories.
2. Category 2 does not use title case whereas the rest do.
3. Confirm column data types.</p>
</div>

In [3]:
### Correcting problems 1 and 2.

categories_df["name"] = "Category_" + categories_df["category_id"].astype(str)

categories_df

   category_id        name
0            1  Category_1
1            2  Category_2
2            3  Category_3
3            4  Category_4
4            5  Category_5

In [4]:
### Confirming Data Types for Problem 3.

categories_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   category_id  5 non-null      int64
 1   name         5 non-null      str
dtypes: int64(1), str(1)
memory usage: 262.0 bytes

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Validated / Complete</h3>
<p style="margin-bottom:0;">Data Types are sensible and Categories table is now clean.</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Table 2: Products</h3>
</div>

In [5]:
products_df = pd.read_csv("challenge_02_data/products.csv")   

products_df

    product_id     sku        name  category_id  vendor_id
0            1  SKU001   Product_1            4          2
1            2  SKU002   Product_2            5          5
2            3  SKU003   Product_3            3          4
3            4  SKU004   Product_4            5          1
4            5  SKU005   Product_5            5          1
5            6  SKU006   Product_6            2          3
6            7  SKU007   Product_7            3          3
7            8  SKU008   Product_8            3          2
8            9  SKU009   Product_9            3          4
9           10  SKU010  Product_10            5          4
10          11  SKU011  Product_11            4          3
11          12  SKU012  Product_12            3          4
12          13  SKU013  Product_13            5          4
13          14  SKU014  Product_14            2          1
14          15  SKU015  Product_15            4          3
15          16  SKU016  Product_16            2          5
16          17  SKU017  Product_17            4          3
17          18  SKU018  Product_18            5          5
18          19  SKU019  Product_19            1          1
19          20  SKU020  Product_20            4          2

<div style="background-color:#f3e8ff; padding:12px; border-left:5px solid #8b5cf6; border-radius:6px;">
<h3 style="margin:0;">Thoughts</h3>
<p style="margin-bottom:0;">

Dataset is small enough to identify problems by eye.

Data appears to be clean.
</p>
</div>

<div style="background-color:#fdecec; padding:12px; border-left:5px solid #dc2626; border-radius:6px;">
<h3 style="margin:0;">Data Quality Issue</h3>
<p style="margin-bottom:0;">Problems Identified: 

1. Confirm column data types.</p>
</div>

In [6]:
### Confirming Data Types for Problem 1.

products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   20 non-null     int64
 1   sku          20 non-null     str
 2   name         20 non-null     str
 3   category_id  20 non-null     int64
 4   vendor_id    20 non-null     int64
dtypes: int64(3), str(2)
memory usage: 1.2 KB

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Validated / Complete</h3>
<p style="margin-bottom:0;">Data Types are sensible and Products table is now clean.</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Table 3: Stores</h3>
</div>

In [7]:
stores_df = pd.read_csv("challenge_02_data/stores.csv")

stores_df

   store_id     name      city
0         1  Store_1   Spokane
1         2  Store_2   Seattle
2         3  Store_3   Spokane
3         4  Store_4  Portland
4         5  Store_5  Portland

<div style="background-color:#f3e8ff; padding:12px; border-left:5px solid #8b5cf6; border-radius:6px;">
<h3 style="margin:0;">Thoughts</h3>
<p style="margin-bottom:0;">

Dataset is small enough to identify problems by eye.

Data appears to be clean.

</p>
</div>

<div style="background-color:#fdecec; padding:12px; border-left:5px solid #dc2626; border-radius:6px;">
<h3 style="margin:0;">Data Quality Issue</h3>
<p style="margin-bottom:0;">Problems Identified: 

1. Confirm column data types.</p>
</div>

In [8]:
### Confirming Data Types for Problem 1.

stores_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   store_id  5 non-null      int64
 1   name      5 non-null      str
 2   city      5 non-null      str
dtypes: int64(1), str(2)
memory usage: 324.0 bytes

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Validated / Complete</h3>
<p style="margin-bottom:0;">Data Types are sensible and Products table is now clean.</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Table 4: Vendors</h3>
</div>

In [9]:
vendors_df = pd.read_csv("challenge_02_data/vendors.csv")

vendors_df.head()

   vendor_id      name
0          1  Vendor_1
1          2  Vendor_2
2          3  Vendor_3
3          4  Vendor_4
4          5  Vendor_5

<div style="background-color:#f3e8ff; padding:12px; border-left:5px solid #8b5cf6; border-radius:6px;">
<h3 style="margin:0;">Thoughts</h3>
<p style="margin-bottom:0;">

Dataset is small enough to identify problems by eye.

Data appears to be clean.

</p>
</div>

<div style="background-color:#fdecec; padding:12px; border-left:5px solid #dc2626; border-radius:6px;">
<h3 style="margin:0;">Data Quality Issue</h3>
<p style="margin-bottom:0;">Problems Identified: 

1. Confirm column data types.</p>
</div>

In [10]:
### Confirming Data Types for Problem 1.

vendors_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   vendor_id  5 non-null      int64
 1   name       5 non-null      str
dtypes: int64(1), str(1)
memory usage: 252.0 bytes

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Validated / Complete</h3>
<p style="margin-bottom:0;">Data Types are sensible and Products table is now clean.</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Table 5: Sales</h3>
</div>

In [11]:
sales_df = pd.read_csv("challenge_02_data/sales.csv")

sales_df

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount
0,1,2024-01-01 00:00:00,1,2,4.0,13.569222,54.276889
1,2,2024-01-01 00:00:00,1,7,4.0,25.768492,103.073967
2,3,2024-01-01 00:00:00,1,15,3.0,45.647379,136.942138
3,4,2024-01-01 00:00:00,1,4,2.0,33.801070,67.602139
4,5,2024-01-01 00:00:00,1,2,2.0,26.963265,53.926530
...,...,...,...,...,...,...,...
2854,1414,2024-01-31 00:00:00,1,17,4.0,16.829888,67.319550
2855,1223,2024-01-27 00:00:00,1,17,3.0,38.706519,116.119556
2856,384,2024-01-08 00:00:00,5,7,2.0,45.891773,91.783547
2857,2339,2024-02-20 00:00:00,1,8,3.0,34.973189,104.919567
2858,2055,2024-02-14 00:00:00,2,13,3.0,20.609367,61.828102

<div style="background-color:#f3e8ff; padding:12px; border-left:5px solid #8b5cf6; border-radius:6px;">
<h3 style="margin:0;">Thoughts</h3>
<p style="margin-bottom:0;">

Dataset is too long to review manually. 

No data quality issues shown in dataframe but review is necessary to confirm.

</p>
</div>

<div style="background-color:#fdecec; padding:12px; border-left:5px solid #dc2626; border-radius:6px;">
<h3 style="margin:0;">Data Quality Issue</h3>
<p style="margin-bottom:0;">Problems Identified: 

1. Confirm column data types.</p>
</div>

In [12]:
### Confirming Data Types for Problem 1.

sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2859 entries, 0 to 2858
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   txn_id       2859 non-null   int64
 1   txn_date     2830 non-null   str
 2   store_id     2859 non-null   int64
 3   product_id   2859 non-null   int64
 4   qty          2802 non-null   float64
 5   unit_price   2803 non-null   float64
 6   line_amount  2859 non-null   float64
dtypes: float64(3), int64(3), str(1)
memory usage: 209.3 KB

<div style="background-color:#fdecec; padding:12px; border-left:5px solid #dc2626; border-radius:6px;">
<h3 style="margin:0;">Data Quality Issue</h3>
<p style="margin-bottom:0;">Problems Identified: 

2. Data type of txn_date is string but should be datetime.
3. Various columns contain null values. These should be filled with appropriate values.</p>
</div>

In [13]:
# Resolving problem 2: Converting the 'txn_date' column to datetime format.

sales_df["txn_date"] = pd.to_datetime(sales_df["txn_date"], errors="coerce")

sales_df.dtypes

txn_id                  int64
txn_date       datetime64[us]
store_id                int64
product_id              int64
qty                   float64
unit_price            float64
line_amount           float64
dtype: object

In [14]:
### Confirm amount of null values in the sales_df DataFrame.

sales_df.isnull().sum()

txn_id          0
txn_date       29
store_id        0
product_id      0
qty            57
unit_price     56
line_amount     0
dtype: int64

In [15]:
### Confirm percentage of null values in the sales_df DataFrame.

sales_df.isnull().mean() * 100

txn_id         0.000000
txn_date       1.014341
store_id       0.000000
product_id     0.000000
qty            1.993704
unit_price     1.958727
line_amount    0.000000
dtype: float64

In [16]:
### View a sample of the rows with null values in the 'txn_date' column to understand the data better.

sales_df[sales_df["txn_date"].isnull()].head(20)

      txn_id txn_date  store_id  product_id  qty  unit_price  line_amount
177      178      NaT         5          13  1.0   17.488947    17.488947
212      213      NaT         3          17  4.0   25.042206   100.168826
237      238      NaT         5          16  1.0    2.124561   212.456117
263      264      NaT         3           6  2.0   29.647924    59.295848
277      278      NaT         5          20  1.0    8.663589     8.663589
310      311      NaT         3          19  4.0   28.050773   112.203093
366      367      NaT         4           5  1.0   21.651759    21.651759
516      517      NaT         4        9999  1.0   38.338845    38.338845
640      641      NaT         3           7  2.0   40.857439    81.714878
672      673      NaT         1          20  4.0   38.892791   155.571163
816      817      NaT         2           7  3.0   25.830135    77.490406
889      890      NaT         5          15  3.0   32.438823    97.316468
906      907      NaT         2           6  3.0         NaN    24.353370
977      978      NaT         5           6  4.0   20.594844    82.379376
1079    1080      NaT         4          12  1.0    5.970342     5.970342
1186    1187      NaT         3           4  3.0   24.864115    74.592346
1368    1369      NaT         1          11  2.0   18.797357    37.594714
1518    1519      NaT         3           1  3.0   40.469397   121.408192
1522    1523      NaT         4          18  2.0    2.919463     5.838927
1705    1706      NaT         5           5  4.0   17.639526    70.558104

In [17]:
### View a sample of the rows with null values in the 'qty' column to understand the data better.

sales_df[sales_df["qty"].isnull()].head(20)

      txn_id   txn_date  store_id  product_id  qty  unit_price  line_amount
57        58 2024-01-02         2        9999  NaN   37.290374   149.161495
113      114 2024-01-03         3           1  NaN   14.011659    42.034977
167      168 2024-01-04         4          13  NaN   18.810476    75.241903
182      183 2024-01-04         5           1  NaN   35.452403    35.452403
200      201 2024-01-05         2          16  NaN   43.506674   130.520022
260      261 2024-01-06         3          11  NaN   15.684568    31.369136
360      361 2024-01-08         3          18  NaN   32.395557    97.186672
462      463 2024-01-10         4          13  NaN   44.174239    44.174239
523      524 2024-01-11         5           9  NaN    5.960410     5.960410
555      556 2024-01-12         4           8  NaN   45.633561   182.534244
678      679 2024-01-15         1           1  NaN   14.629403    43.888210
726      727 2024-01-16         3          10  NaN    8.390960     8.390960
759      760 2024-01-17         2           3  NaN   41.165453    82.330906
942      943 2024-01-21         1          14  NaN   23.478471    70.435412
1030    1031 2024-01-22         5          14  NaN   21.564042    64.692126
1039    1040 2024-01-22         5          11  NaN   35.241557   105.724670
1064    1065 2024-01-23         3          19  NaN   38.461349    38.461349
1168    1169 2024-01-26         1          10  NaN   15.866477    63.465908
1213    1214 2024-01-26         5          15  NaN    8.237186     8.237186
1267    1268 2024-01-28         1          10  NaN   35.918234    35.918234

In [18]:
### View a sample of the rows with null values in the 'unit_price' column to understand the data better.

sales_df[sales_df["unit_price"].isnull()].head(20)

      txn_id   txn_date  store_id  product_id  qty  unit_price  line_amount
6          7 2024-01-01         1          18  2.0         NaN    47.176397
87        88 2024-01-03         1           1  4.0         NaN   101.173736
118      119 2024-01-03         4           5  2.0         NaN     5.381775
128      129 2024-01-03         5          16  3.0         NaN   141.972230
210      211 2024-01-05         2           3  3.0         NaN    50.319923
267      268 2024-01-06         3          15  3.0         NaN    88.312227
312      313 2024-01-07         3          11  2.0         NaN    91.211254
352      353 2024-01-08         2           7  1.0         NaN    21.583256
432      433 2024-01-09         5           5  1.0         NaN    15.308751
478      479 2024-01-10         5           9  4.0         NaN   169.303329
485      486 2024-01-11         1          15  1.0         NaN    23.405999
629      630 2024-01-14         1          10  3.0         NaN    81.623527
713      714 2024-01-16         1          18  3.0         NaN   120.061483
906      907        NaT         2           6  3.0         NaN    24.353370
930      931 2024-01-20         4           9  3.0         NaN   134.523354
935      936 2024-01-20         5           3  2.0         NaN    29.216862
976      977 2024-01-21         5          17  3.0         NaN    55.416099
1011    1012 2024-01-22         2          14  3.0         NaN    44.915668
1127    1128 2024-01-24         5          13  3.0         NaN    14.599174
1221    1222 2024-01-27         1          20  4.0         NaN    38.206646

In [19]:
### View all rows where the store_id is greater than 5 to understand if rows do not belong to one of our the stores in our dataset.

sales_df[
    ~sales_df["store_id"].isin(stores_df["store_id"])
]

      txn_id   txn_date  store_id  product_id  qty  unit_price  line_amount
71        72 2024-01-02      9999           9  4.0   36.184603   144.738410
132      133 2024-01-03      9999           3  1.0   48.137147    48.137147
406      407 2024-01-09      9999          16  2.0   49.067686    98.135373
807      808 2024-01-18      9999          20  1.0   49.023042    49.023042
1077    1078 2024-01-23      9999          17  3.0   29.996793    89.990379
1372    1373 2024-01-30      9999          16  1.0   29.888724    29.888724
1686    1687 2024-02-06      9999          20  2.0    4.159847     8.319695
1692    1693 2024-02-06      9999           4  4.0   25.644752   102.579009
1851    1852 2024-02-09      9999          15  4.0   14.217946    56.871784
2002    2003 2024-02-13      9999           2  1.0   47.027079    47.027079
2016    2017 2024-02-13      9999           1  3.0    4.675561    14.026683
2105    2106 2024-02-15      9999          18  1.0   29.403539    29.403539
2427    2428 2024-02-21      9999           9  3.0         NaN   128.627722
2601    2602 2024-02-25      9999          11  4.0   26.042077   104.168308

In [20]:
### View all rows where the product_id is greater than 20 to understand if rows do not belong to one of our the products in our dataset.

sales_df[sales_df["product_id"] > 20]

      txn_id   txn_date  store_id  product_id  qty  unit_price  line_amount
44        45 2024-01-01         5        9999  2.0   26.128593    52.257186
57        58 2024-01-02         2        9999  NaN   37.290374   149.161495
70        71 2024-01-02         4        9999  2.0   23.524359    47.048718
111      112 2024-01-03         3        9999  2.0   48.207124    96.414248
120      121 2024-01-03         4        9999  2.0   43.062108    86.124216
178      179 2024-01-04         5        9999  2.0   46.382880    92.765760
332      333 2024-01-07         5        9999  4.0   12.781032    51.124126
410      411 2024-01-09         3        9999  2.0    7.785084    15.570168
516      517        NaT         4        9999  1.0   38.338845    38.338845
567      568 2024-01-12         5        9999  1.0   13.938285    13.938285
580      581 2024-01-13         1        9999  2.0   47.686966    95.373931
590      591 2024-01-13         2        9999  1.0   41.882105    41.882105
594      595 2024-01-13         3        9999  1.0   29.704891    29.704891
1397    1398 2024-01-30         4        9999  1.0   44.200917    44.200917
1398    1399 2024-01-30         4        9999  3.0   28.752184    86.256552
1542    1543 2024-02-03         1        9999  1.0   38.056503    38.056503
1622    1623 2024-02-05         1        9999  1.0   12.688452    12.688452
1704    1705 2024-02-06         5        9999  3.0    5.920029    17.760088
1731    1732 2024-02-07         4        9999  2.0    6.440021    12.880042
1761    1762 2024-02-08         2        9999  3.0   33.665133   100.995399
1816    1817 2024-02-09         2        9999  4.0    7.917621    31.670486
1892    1893 2024-02-10         5        9999  2.0   29.602908    59.205815
2160    2161 2024-02-16         3        9999  2.0   44.448485    88.896969
2269    2270 2024-02-18         3        9999  1.0    7.011938     7.011938
2445    2446 2024-02-22         2        9999  3.0   12.450795    37.352385
2470    2471 2024-02-22         5        9999  NaN   31.882256    31.882256
2481    2482 2024-02-23         1        9999  2.0   21.183584    42.367168
2653    2654 2024-02-26         4        9999  4.0   38.007720   152.030880
2815    1293 2024-01-28         3        9999  3.0   42.247608   126.742824

In [21]:
### View all rows where both 'qty' and 'unit_price' are null. This allows us to understand if there are any rows that could not be
### recalculated due to missing values in both columns. This is important for data integrity and analysis.

sales_df[sales_df["qty"].isnull() & sales_df["unit_price"].isnull()]

Empty DataFrame
Columns: [txn_id, txn_date, store_id, product_id, qty, unit_price, line_amount]
Index: []

In [22]:
### Check whether every transaction ID is unique.

sales_df["txn_id"].is_unique

False

In [23]:
### Find duplicate rows in the Sales table.

sales_df[sales_df.duplicated(keep=False)]

      txn_id   txn_date  store_id  product_id  qty  unit_price  line_amount
10        11 2024-01-01         1          18  3.0   41.779400   125.338201
93        94 2024-01-03         1           1  1.0   35.719236    35.719236
236      237 2024-01-05         5          15  4.0   43.931774   175.727096
354      355 2024-01-08         2           8  2.0   18.285020    36.570040
369      370 2024-01-08         4          12  4.0    7.483420    29.933682
...      ...        ...       ...         ...  ...         ...          ...
2854    1414 2024-01-31         1          17  4.0   16.829888    67.319550
2855    1223 2024-01-27         1          17  3.0   38.706519   116.119556
2856     384 2024-01-08         5           7  2.0   45.891773    91.783547
2857    2339 2024-02-20         1           8  3.0   34.973189   104.919567
2858    2055 2024-02-14         2          13  3.0   20.609367    61.828102

[94 rows x 7 columns]

In [24]:
### Create a dataframe containing rows where qty and unit_price are both present.

complete_sales = sales_df[
    sales_df["qty"].notnull()
    & sales_df["unit_price"].notnull()
]

In [25]:
### Calculate the expected amount.

complete_sales = complete_sales.copy()

complete_sales["expected_amount"] = (
    complete_sales["qty"] * complete_sales["unit_price"]
)

In [26]:
### Compare the recorded amount with the calculated  amount.

complete_sales["difference"] = (
    complete_sales["line_amount"]
    - complete_sales["expected_amount"]
)

In [27]:
### Review rows where the difference between the recorded and calculated amounts is greater than 0.01.

complete_sales[
    complete_sales["difference"].abs() > 0.01
]

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,expected_amount,difference
11,12,2024-01-01,1,13,1000.0,16.221128,16.221128,16221.128274,-16204.907146
152,153,2024-01-04,2,19,2000.0,32.328186,64.656372,64656.372368,-64591.715996
184,185,2024-01-04,5,11,4000.0,48.017716,192.070862,192070.862222,-191878.791360
237,238,NaT,5,16,1.0,2.124561,212.456117,2.124561,210.331556
271,272,2024-01-06,4,1,2000.0,38.853416,77.706832,77706.832139,-77629.125306
477,478,2024-01-10,5,19,2000.0,2.884530,5.769061,5769.060999,-5763.291938
654,655,2024-01-14,4,14,4000.0,6.111596,24.446384,24446.383923,-24421.937539
733,734,2024-01-16,3,13,3.0,7.073287,2121.986111,21.219861,2100.766250
746,747,2024-01-16,4,8,1000.0,48.847561,48.847561,48847.560781,-48798.713220
754,755,2024-01-17,1,8,2000.0,12.781549,25.563099,25563.098737,-25537.535638
775,776,2024-01-17,4,3,4000.0,44.231191,176.924765,176924.765301,-176747.840536
778,779,2024-01-17,4,2,1000.0,20.012475,20.012475,20012.475413,-19992.462938
780,781,2024-01-17,4,10,2000.0,42.318271,84.636542,84636.542107,-84551.905565
989,990,2024-01-22,1,19,1000.0,26.827490,26.827490,26827.490322,-26800.662832
1087,1088,2024-01-23,5,10,3000.0,10.013748,30.041245,30041.244780,-30011.203535
1389,1390,2024-01-30,3,6,3.0,32.545966,9763.789654,97.637897,9666.151758
1407,1408,2024-01-30,5,3,3000.0,3.936840,11.810519,11810.519068,-11798.708549
1454,1455,2024-02-01,2,3,1000.0,38.446040,38.446040,38446.040332,-38407.594292
1687,1688,2024-02-06,4,9,4.0,18.383295,7353.318002,73.533180,7279.784822
1711,1712,2024-02-07,1,13,3000.0,21.297306,63.891919,63891.919232,-63828.027313
1758,1759,2024-02-08,1,17,3000.0,23.683495,71.050485,71050.484541,-70979.434057
1799,1800,2024-02-08,5,19,3000.0,24.960103,74.880309,74880.309361,-74805.429051
1847,1848,2024-02-09,4,11,3.0,22.082698,6624.809281,66.248093,6558.561188
1854,1855,2024-02-10,1,8,4000.0,8.264219,33.056875,33056.875450,-33023.818575
1929,1930,2024-02-11,4,18,3000.0,5.403966,16.211898,16211.898166,-16195.686268
1942,1943,2024-02-11,5,2,4.0,26.617988,10647.195052,106.471951,10540.723102
1990,1991,2024-02-12,5,2,2000.0,11.325131,22.650263,22650.262816,-22627.612553
2005,2006,2024-02-13,2,1,1000.0,17.057750,17.057750,17057.749988,-17040.692238
2006,2007,2024-02-13,2,6,3000.0,31.720066,95.160198,95160.198371,-95065.038173
2046,2047,2024-02-14,2,13,4.0,12.369509,4947.803656,49.478037,4898.325619
2106,2107,2024-02-15,3,14,2000.0,17.145593,34.291185,34291.185344,-34256.894158
2157,2158,2024-02-16,3,5,2.0,24.766816,4953.363183,49.533632,4903.829551
2169,2170,2024-02-16,4,15,1000.0,43.489581,43.489581,43489.580790,-43446.091209
2220,2221,2024-02-17,3,11,3.0,2.655761,796.728271,7.967283,788.760988
2239,2240,2024-02-17,5,12,2.0,17.395212,3479.042390,34.790424,3444.251966
2259,2260,2024-02-18,2,3,3.0,14.854039,4456.211633,44.562116,4411.649517
2286,2287,2024-02-18,5,18,3000.0,14.086725,42.260174,42260.174311,-42217.914137
2451,2452,2024-02-22,3,9,3.0,24.478428,7343.528517,73.435285,7270.093232
2509,2510,2024-02-23,5,18,1000.0,38.425670,38.425670,38425.670452,-38387.244782
2522,2523,2024-02-24,1,3,2.0,15.937370,3187.474100,31.874741,3155.599359
2649,2650,2024-02-26,4,19,3.0,44.818825,13445.647587,134.456476,13311.191111
2727,2728,2024-02-28,2,20,1000.0,28.885567,28.885567,28885.567184,-28856.681617
2761,2762,2024-02-29,1,18,2000.0,17.389756,34.779511,34779.511029,-34744.731518

In [28]:
# View missing quantities and calculate what qty would need to be.

missing_qty = sales_df[sales_df["qty"].isnull()].copy()

missing_qty["calculated_qty"] = (
    missing_qty["line_amount"]
    / missing_qty["unit_price"]
)

missing_qty

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,calculated_qty
57,58,2024-01-02,2,9999,NaN,37.290374,149.161495,4.0
113,114,2024-01-03,3,1,NaN,14.011659,42.034977,3.0
167,168,2024-01-04,4,13,NaN,18.810476,75.241903,4.0
182,183,2024-01-04,5,1,NaN,35.452403,35.452403,1.0
200,201,2024-01-05,2,16,NaN,43.506674,130.520022,3.0
260,261,2024-01-06,3,11,NaN,15.684568,31.369136,2.0
360,361,2024-01-08,3,18,NaN,32.395557,97.186672,3.0
462,463,2024-01-10,4,13,NaN,44.174239,44.174239,1.0
523,524,2024-01-11,5,9,NaN,5.960410,5.960410,1.0
555,556,2024-01-12,4,8,NaN,45.633561,182.534244,4.0
678,679,2024-01-15,1,1,NaN,14.629403,43.888210,3.0
726,727,2024-01-16,3,10,NaN,8.390960,8.390960,1.0
759,760,2024-01-17,2,3,NaN,41.165453,82.330906,2.0
942,943,2024-01-21,1,14,NaN,23.478471,70.435412,3.0
1030,1031,2024-01-22,5,14,NaN,21.564042,64.692126,3.0
1039,1040,2024-01-22,5,11,NaN,35.241557,105.724670,3.0
1064,1065,2024-01-23,3,19,NaN,38.461349,38.461349,1.0
1168,1169,2024-01-26,1,10,NaN,15.866477,63.465908,4.0
1213,1214,2024-01-26,5,15,NaN,8.237186,8.237186,1.0
1267,1268,2024-01-28,1,10,NaN,35.918234,35.918234,1.0
1277,1278,2024-01-28,2,4,NaN,42.310477,42.310477,1.0
1364,1365,2024-01-29,5,15,NaN,49.864753,199.459012,4.0
1373,1374,2024-01-30,2,5,NaN,38.083856,152.335423,4.0
1383,1384,2024-01-30,2,8,NaN,17.063687,68.254747,4.0
1401,1402,2024-01-30,5,7,NaN,34.005052,136.020207,4.0
1493,1494,2024-02-01,5,20,NaN,30.268788,90.806363,3.0
1655,1656,2024-02-05,4,2,NaN,13.832955,13.832955,1.0
1765,1766,NaT,2,10,NaN,30.886723,30.886723,1.0
1781,1782,2024-02-08,3,7,NaN,7.968600,7.968600,1.0
1839,1840,2024-02-09,4,20,NaN,10.698827,10.698827,1.0
1883,1884,2024-02-10,4,14,NaN,45.074514,180.298058,4.0
1918,1919,2024-02-11,3,13,NaN,43.264620,173.058480,4.0
1967,1968,2024-02-12,3,19,NaN,41.305725,165.222900,4.0
1999,2000,2024-02-13,2,1,NaN,49.100364,196.401455,4.0
2136,2137,2024-02-16,1,10,NaN,2.421306,2.421306,1.0
2144,2145,2024-02-16,1,1,NaN,35.638804,106.916412,3.0
2167,2168,2024-02-16,4,16,NaN,26.695501,80.086503,3.0
2183,2184,2024-02-16,5,2,NaN,18.465282,36.930564,2.0
2266,2267,2024-02-18,3,15,NaN,40.958097,122.874290,3.0
2283,2284,2024-02-18,5,20,NaN,23.055153,23.055153,1.0
2340,2341,2024-02-20,1,9,NaN,35.305432,105.916295,3.0
2367,2368,2024-02-20,4,4,NaN,23.738401,94.953605,4.0
2373,2374,2024-02-20,4,11,NaN,11.464783,11.464783,1.0
2406,2407,2024-02-21,2,10,NaN,37.248802,148.995207,4.0
2470,2471,2024-02-22,5,9999,NaN,31.882256,31.882256,1.0
2471,2472,2024-02-23,1,18,NaN,31.939699,31.939699,1.0
2475,2476,2024-02-23,1,8,NaN,46.951680,93.903360,2.0
2521,2522,2024-02-24,1,17,NaN,35.099987,140.399949,4.0
2527,2528,2024-02-24,1,6,NaN,25.485405,76.456214,3.0
2563,2564,2024-02-24,4,3,NaN,10.199058,40.796232,4.0
2634,2635,2024-02-26,2,20,NaN,43.673748,174.694991,4.0
2665,2666,2024-02-26,5,6,NaN,44.597201,89.194402,2.0
2671,2672,2024-02-27,1,9,NaN,8.054608,16.109215,2.0
2708,2709,2024-02-27,4,2,NaN,10.971550,10.971550,1.0
2736,2737,2024-02-28,3,5,NaN,13.994605,27.989210,2.0
2776,2777,2024-02-29,2,10,NaN,34.722793,138.891171,4.0
2843,1031,2024-01-22,5,14,NaN,21.564042,64.692126,3.0

In [29]:
### Confirm the calculated quantities are correct by checking the value counts of the calculated_qty column.
missing_qty["calculated_qty"].value_counts()

calculated_qty
1.0    18
4.0    16
3.0     8
2.0     7
3.0     3
3.0     3
4.0     2
Name: count, dtype: int64

In [30]:
### Confirm the calculated quantities are correct by checking the value counts of the calculated_qty column, rounding to the nearest whole number, and sorting the index.

missing_qty["calculated_qty"].round().value_counts().sort_index()

calculated_qty
1.0    18
2.0     7
3.0    14
4.0    18
Name: count, dtype: int64

In [31]:
### Flag rows where quantity was originally missing

sales_df["qty_was_missing"] = sales_df["qty"].isnull()

In [32]:
### Recalculate missing quantities using line_amount / unit_price

sales_df.loc[sales_df["qty"].isnull(), "qty"] = (
    sales_df["line_amount"] / sales_df["unit_price"]
).round()

In [33]:
sales_df["qty"].isnull().sum()

np.int64(0)

In [34]:
sales_df[sales_df["qty_was_missing"]]

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,qty_was_missing
57,58,2024-01-02,2,9999,4.0,37.290374,149.161495,True
113,114,2024-01-03,3,1,3.0,14.011659,42.034977,True
167,168,2024-01-04,4,13,4.0,18.810476,75.241903,True
182,183,2024-01-04,5,1,1.0,35.452403,35.452403,True
200,201,2024-01-05,2,16,3.0,43.506674,130.520022,True
260,261,2024-01-06,3,11,2.0,15.684568,31.369136,True
360,361,2024-01-08,3,18,3.0,32.395557,97.186672,True
462,463,2024-01-10,4,13,1.0,44.174239,44.174239,True
523,524,2024-01-11,5,9,1.0,5.960410,5.960410,True
555,556,2024-01-12,4,8,4.0,45.633561,182.534244,True
678,679,2024-01-15,1,1,3.0,14.629403,43.888210,True
726,727,2024-01-16,3,10,1.0,8.390960,8.390960,True
759,760,2024-01-17,2,3,2.0,41.165453,82.330906,True
942,943,2024-01-21,1,14,3.0,23.478471,70.435412,True
1030,1031,2024-01-22,5,14,3.0,21.564042,64.692126,True
1039,1040,2024-01-22,5,11,3.0,35.241557,105.724670,True
1064,1065,2024-01-23,3,19,1.0,38.461349,38.461349,True
1168,1169,2024-01-26,1,10,4.0,15.866477,63.465908,True
1213,1214,2024-01-26,5,15,1.0,8.237186,8.237186,True
1267,1268,2024-01-28,1,10,1.0,35.918234,35.918234,True
1277,1278,2024-01-28,2,4,1.0,42.310477,42.310477,True
1364,1365,2024-01-29,5,15,4.0,49.864753,199.459012,True
1373,1374,2024-01-30,2,5,4.0,38.083856,152.335423,True
1383,1384,2024-01-30,2,8,4.0,17.063687,68.254747,True
1401,1402,2024-01-30,5,7,4.0,34.005052,136.020207,True
1493,1494,2024-02-01,5,20,3.0,30.268788,90.806363,True
1655,1656,2024-02-05,4,2,1.0,13.832955,13.832955,True
1765,1766,NaT,2,10,1.0,30.886723,30.886723,True
1781,1782,2024-02-08,3,7,1.0,7.968600,7.968600,True
1839,1840,2024-02-09,4,20,1.0,10.698827,10.698827,True
1883,1884,2024-02-10,4,14,4.0,45.074514,180.298058,True
1918,1919,2024-02-11,3,13,4.0,43.264620,173.058480,True
1967,1968,2024-02-12,3,19,4.0,41.305725,165.222900,True
1999,2000,2024-02-13,2,1,4.0,49.100364,196.401455,True
2136,2137,2024-02-16,1,10,1.0,2.421306,2.421306,True
2144,2145,2024-02-16,1,1,3.0,35.638804,106.916412,True
2167,2168,2024-02-16,4,16,3.0,26.695501,80.086503,True
2183,2184,2024-02-16,5,2,2.0,18.465282,36.930564,True
2266,2267,2024-02-18,3,15,3.0,40.958097,122.874290,True
2283,2284,2024-02-18,5,20,1.0,23.055153,23.055153,True
2340,2341,2024-02-20,1,9,3.0,35.305432,105.916295,True
2367,2368,2024-02-20,4,4,4.0,23.738401,94.953605,True
2373,2374,2024-02-20,4,11,1.0,11.464783,11.464783,True
2406,2407,2024-02-21,2,10,4.0,37.248802,148.995207,True
2470,2471,2024-02-22,5,9999,1.0,31.882256,31.882256,True
2471,2472,2024-02-23,1,18,1.0,31.939699,31.939699,True
2475,2476,2024-02-23,1,8,2.0,46.951680,93.903360,True
2521,2522,2024-02-24,1,17,4.0,35.099987,140.399949,True
2527,2528,2024-02-24,1,6,3.0,25.485405,76.456214,True
2563,2564,2024-02-24,4,3,4.0,10.199058,40.796232,True
2634,2635,2024-02-26,2,20,4.0,43.673748,174.694991,True
2665,2666,2024-02-26,5,6,2.0,44.597201,89.194402,True
2671,2672,2024-02-27,1,9,2.0,8.054608,16.109215,True
2708,2709,2024-02-27,4,2,1.0,10.971550,10.971550,True
2736,2737,2024-02-28,3,5,2.0,13.994605,27.989210,True
2776,2777,2024-02-29,2,10,4.0,34.722793,138.891171,True
2843,1031,2024-01-22,5,14,3.0,21.564042,64.692126,True

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Missing Quantity Values Resolved</h3>
<p style="margin-bottom:0;">
57 missing quantity values were identified. As line_amount and unit_price were available for every affected record, quantity was reconstructed using qty = line_amount / unit_price. All calculated values resolved to valid floating point quantities.
</p>
</div>

<div style="background-color:#f3e8ff; padding:12px; border-left:5px solid #8b5cf6; border-radius:6px;">
<h3 style="margin:0;">Step 4: Complete Sales Data Integrity Checks</h3>
<p style="margin-bottom:0;">
Confirm duplicate records, repair values only where there is enough evidence, validate the sales calculation and document any issues that cannot be safely corrected.
</p>
</div>

In [35]:
### Define the original Sales columns so audit flags do not affect duplicate checks.

sales_columns = [
    "txn_id",
    "txn_date",
    "store_id",
    "product_id",
    "qty",
    "unit_price",
    "line_amount"
]

rows_original = len(sales_df)
qty_values_reconstructed = int(sales_df["qty_was_missing"].sum())

exact_duplicate_rows = sales_df[
    sales_df.duplicated(subset=sales_columns, keep=False)
].sort_values("txn_id")

exact_duplicate_rows

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,qty_was_missing
10,11,2024-01-01,1,18,3.0,41.779400,125.338201,False
2811,11,2024-01-01,1,18,3.0,41.779400,125.338201,False
2814,94,2024-01-03,1,1,1.0,35.719236,35.719236,False
93,94,2024-01-03,1,1,1.0,35.719236,35.719236,False
236,237,2024-01-05,5,15,4.0,43.931774,175.727096,False
...,...,...,...,...,...,...,...,...
2732,2733,2024-02-28,3,8,4.0,26.146100,104.584400,False
2773,2774,2024-02-29,2,1,1.0,38.112594,38.112594,False
2840,2774,2024-02-29,2,1,1.0,38.112594,38.112594,False
2812,2780,2024-02-29,3,10,4.0,36.539803,146.159211,False
2779,2780,2024-02-29,3,10,4.0,36.539803,146.159211,False

In [36]:
### Remove only the second copy of each confirmed exact duplicate.

exact_duplicates_removed = int(
    sales_df.duplicated(subset=sales_columns).sum()
)

sales_df = sales_df.drop_duplicates(
    subset=sales_columns
).copy()

pd.Series({
    "exact_duplicates_removed": exact_duplicates_removed,
    "exact_duplicates_remaining": sales_df.duplicated(subset=sales_columns).sum(),
    "rows_remaining": len(sales_df)
})

exact_duplicates_removed        47
exact_duplicates_remaining       0
rows_remaining                2812
dtype: int64

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Exact Duplicate Records Removed</h3>
<p style="margin-bottom:0;">
47 rows were confirmed as exact copies across the original Sales columns. Only the additional copies were removed, leaving 2,812 rows for the remaining checks.
</p>
</div>

In [37]:
### Check duplicate transaction IDs again after removing exact duplicate rows.

duplicate_txn_rows = sales_df[
    sales_df["txn_id"].duplicated(keep=False)
].sort_values("txn_id")

print("Duplicate transaction ID groups:", duplicate_txn_rows["txn_id"].nunique())
duplicate_txn_rows

Duplicate transaction ID groups: 3

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,qty_was_missing
406,407,2024-01-09,9999,16,2.0,49.067686,98.135373,False
2829,407,2024-01-09,2,16,2.0,49.067686,98.135373,False
2825,734,2024-01-16,3,13,3.0,7.073287,21.219861,False
733,734,2024-01-16,3,13,3.0,7.073287,2121.986111,False
2815,1293,2024-01-28,3,9999,3.0,42.247608,126.742824,False
1292,1293,2024-01-28,3,16,3.0,42.247608,126.742824,False

<div style="background-color:#f3e8ff; padding:12px; border-left:5px solid #8b5cf6; border-radius:6px;">
<h3 style="margin:0;">Duplicate Transaction ID Investigation</h3>
<p style="margin-bottom:0;">
Three transaction IDs still appear twice. Transaction 407 contains one valid store ID and one 9999 store ID, transaction 1293 contains one valid product ID and one 9999 product ID, and transaction 734 contains one valid line amount and one amount multiplied by 100. These rows will not be removed until the matching records have been used as evidence for the repairs.
</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Missing Unit Price Values</h3>
</div>

In [38]:
import numpy as np

### Calculate the missing unit prices without changing the Sales table yet.

missing_price = sales_df[sales_df["unit_price"].isnull()].copy()

missing_price["calculated_unit_price"] = (
    missing_price["line_amount"]
    / missing_price["qty"]
)

missing_price[[
    "txn_id",
    "product_id",
    "qty",
    "unit_price",
    "line_amount",
    "calculated_unit_price"
]]

      txn_id  product_id  qty  unit_price  line_amount  calculated_unit_price
6          7          18  2.0         NaN    47.176397              23.588198
87        88           1  4.0         NaN   101.173736              25.293434
118      119           5  2.0         NaN     5.381775               2.690887
128      129          16  3.0         NaN   141.972230              47.324077
210      211           3  3.0         NaN    50.319923              16.773308
267      268          15  3.0         NaN    88.312227              29.437409
312      313          11  2.0         NaN    91.211254              45.605627
352      353           7  1.0         NaN    21.583256              21.583256
432      433           5  1.0         NaN    15.308751              15.308751
478      479           9  4.0         NaN   169.303329              42.325832
485      486          15  1.0         NaN    23.405999              23.405999
629      630          10  3.0         NaN    81.623527              27.207842
713      714          18  3.0         NaN   120.061483              40.020494
906      907           6  3.0         NaN    24.353370               8.117790
930      931           9  3.0         NaN   134.523354              44.841118
935      936           3  2.0         NaN    29.216862              14.608431
976      977          17  3.0         NaN    55.416099              18.472033
1011    1012          14  3.0         NaN    44.915668              14.971889
1127    1128          13  3.0         NaN    14.599174               4.866391
1221    1222          20  4.0         NaN    38.206646               9.551661
1233    1234           6  4.0         NaN    42.417077              10.604269
1315    1316          12  4.0         NaN    93.114850              23.278712
1375    1376          17  3.0         NaN   102.646676              34.215559
1384    1385           8  1.0         NaN    12.315807              12.315807
1386    1387           2  2.0         NaN    40.748681              20.374341
1406    1407          10  3.0         NaN   149.658475              49.886158
1446    1447           8  3.0         NaN   128.023862              42.674621
1617    1618          20  2.0         NaN    79.196606              39.598303
1688    1689           2  4.0         NaN    71.738529              17.934632
1733    1734          20  3.0         NaN    94.863256              31.621085
1738    1739          19  4.0         NaN    28.252818               7.063205
1741    1742           2  3.0         NaN    45.137258              15.045753
1808    1809           3  1.0         NaN    28.557951              28.557951
1817    1818          16  2.0         NaN    27.601354              13.800677
1890    1891          18  4.0         NaN    83.562625              20.890656
2017    2018           5  4.0         NaN    54.234333              13.558583
2095    2096           8  1.0         NaN    26.864501              26.864501
2129    2130           4  1.0         NaN    19.903992              19.903992
2170    2171           4  4.0         NaN    99.220806              24.805202
2177    2178          15  1.0         NaN    24.531528              24.531528
2216    2217           5  2.0         NaN    51.839971              25.919985
2236    2237          16  4.0         NaN    52.221291              13.055323
2305    2306           6  2.0         NaN     6.077974               3.038987
2353    2354          12  1.0         NaN    45.912078              45.912078
2427    2428           9  3.0         NaN   128.627722              42.875907
2489    2490           6  1.0         NaN     9.170319               9.170319
2519    2520          20  1.0         NaN     7.127408               7.127408
2566    2567          14  4.0         NaN    54.284354              13.571089
2624    2625          19  1.0         NaN    19.279636              19.279636
2723    2724          14  3.0         NaN    58.745240              19.581747
2735    2736          17  3.0         NaN   109.538800              36.512933
2757    2758           6  3.0         NaN   120.355377              40.118459
2758    2759           6  3.0         NaN    19.031469               6.343823
2767    2768           4  3.0         NaN   140.300116              46.766705
2791    2792          19  1.0         NaN    44.665045              44.665045
2802    2803           5  1.0         NaN     7.480821               7.480821

In [39]:
### Confirm the calculated prices are positive and within the existing price range.

print(missing_price["calculated_unit_price"].describe())

missing_price[
    missing_price["calculated_unit_price"] <= 0
]

count    56.000000
mean     23.838218
std      13.565693
min       2.690887
25%      13.567962
50%      21.236956
75%      34.789902
max      49.886158
Name: calculated_unit_price, dtype: float64

Empty DataFrame
Columns: [txn_id, txn_date, store_id, product_id, qty, unit_price, line_amount, qty_was_missing, calculated_unit_price]
Index: []

In [40]:
### Flag and reconstruct the missing unit prices using line_amount / qty.

sales_df["unit_price_was_missing"] = sales_df["unit_price"].isnull()
unit_price_values_reconstructed = int(sales_df["unit_price_was_missing"].sum())

sales_df.loc[
    sales_df["unit_price"].isnull(),
    "unit_price"
] = (
    sales_df["line_amount"]
    / sales_df["qty"]
)

pd.Series({
    "unit_price_values_reconstructed": unit_price_values_reconstructed,
    "missing_unit_prices_remaining": sales_df["unit_price"].isnull().sum(),
    "reconstructed_calculations_match": np.isclose(
        sales_df.loc[sales_df["unit_price_was_missing"], "line_amount"],
        sales_df.loc[sales_df["unit_price_was_missing"], "qty"]
        * sales_df.loc[sales_df["unit_price_was_missing"], "unit_price"]
    ).all()
})

unit_price_values_reconstructed       56
missing_unit_prices_remaining          0
reconstructed_calculations_match    True
dtype: object

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Missing Unit Price Values Resolved</h3>
<p style="margin-bottom:0;">
56 missing unit prices were reconstructed using unit_price = line_amount / qty. Every calculated value was positive and fell within the existing unit price range.
</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Sales Calculation Validation</h3>
</div>

In [41]:
### Find all rows where qty * unit_price does not equal line_amount.

expected_line_amount = sales_df["qty"] * sales_df["unit_price"]

calculation_errors = sales_df[
    ~np.isclose(
        sales_df["line_amount"],
        expected_line_amount,
        rtol=1e-9,
        atol=0.01
    )
][sales_columns].copy()

calculation_errors["expected_line_amount"] = (
    calculation_errors["qty"]
    * calculation_errors["unit_price"]
)

calculation_errors["difference"] = (
    calculation_errors["line_amount"]
    - calculation_errors["expected_line_amount"]
)

calculation_errors

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,expected_line_amount,difference
11,12,2024-01-01,1,13,1000.0,16.221128,16.221128,16221.128274,-16204.907146
152,153,2024-01-04,2,19,2000.0,32.328186,64.656372,64656.372368,-64591.715996
184,185,2024-01-04,5,11,4000.0,48.017716,192.070862,192070.862222,-191878.791360
237,238,NaT,5,16,1.0,2.124561,212.456117,2.124561,210.331556
271,272,2024-01-06,4,1,2000.0,38.853416,77.706832,77706.832139,-77629.125306
477,478,2024-01-10,5,19,2000.0,2.884530,5.769061,5769.060999,-5763.291938
654,655,2024-01-14,4,14,4000.0,6.111596,24.446384,24446.383923,-24421.937539
733,734,2024-01-16,3,13,3.0,7.073287,2121.986111,21.219861,2100.766250
746,747,2024-01-16,4,8,1000.0,48.847561,48.847561,48847.560781,-48798.713220
754,755,2024-01-17,1,8,2000.0,12.781549,25.563099,25563.098737,-25537.535638
775,776,2024-01-17,4,3,4000.0,44.231191,176.924765,176924.765301,-176747.840536
778,779,2024-01-17,4,2,1000.0,20.012475,20.012475,20012.475413,-19992.462938
780,781,2024-01-17,4,10,2000.0,42.318271,84.636542,84636.542107,-84551.905565
989,990,2024-01-22,1,19,1000.0,26.827490,26.827490,26827.490322,-26800.662832
1087,1088,2024-01-23,5,10,3000.0,10.013748,30.041245,30041.244780,-30011.203535
1389,1390,2024-01-30,3,6,3.0,32.545966,9763.789654,97.637897,9666.151758
1407,1408,2024-01-30,5,3,3000.0,3.936840,11.810519,11810.519068,-11798.708549
1454,1455,2024-02-01,2,3,1000.0,38.446040,38.446040,38446.040332,-38407.594292
1687,1688,2024-02-06,4,9,4.0,18.383295,7353.318002,73.533180,7279.784822
1711,1712,2024-02-07,1,13,3000.0,21.297306,63.891919,63891.919232,-63828.027313
1758,1759,2024-02-08,1,17,3000.0,23.683495,71.050485,71050.484541,-70979.434057
1799,1800,2024-02-08,5,19,3000.0,24.960103,74.880309,74880.309361,-74805.429051
1847,1848,2024-02-09,4,11,3.0,22.082698,6624.809281,66.248093,6558.561188
1854,1855,2024-02-10,1,8,4000.0,8.264219,33.056875,33056.875450,-33023.818575
1929,1930,2024-02-11,4,18,3000.0,5.403966,16.211898,16211.898166,-16195.686268
1942,1943,2024-02-11,5,2,4.0,26.617988,10647.195052,106.471951,10540.723102
1990,1991,2024-02-12,5,2,2000.0,11.325131,22.650263,22650.262816,-22627.612553
2005,2006,2024-02-13,2,1,1000.0,17.057750,17.057750,17057.749988,-17040.692238
2006,2007,2024-02-13,2,6,3000.0,31.720066,95.160198,95160.198371,-95065.038173
2046,2047,2024-02-14,2,13,4.0,12.369509,4947.803656,49.478037,4898.325619
2106,2107,2024-02-15,3,14,2000.0,17.145593,34.291185,34291.185344,-34256.894158
2157,2158,2024-02-16,3,5,2.0,24.766816,4953.363183,49.533632,4903.829551
2169,2170,2024-02-16,4,15,1000.0,43.489581,43.489581,43489.580790,-43446.091209
2220,2221,2024-02-17,3,11,3.0,2.655761,796.728271,7.967283,788.760988
2239,2240,2024-02-17,5,12,2.0,17.395212,3479.042390,34.790424,3444.251966
2259,2260,2024-02-18,2,3,3.0,14.854039,4456.211633,44.562116,4411.649517
2286,2287,2024-02-18,5,18,3000.0,14.086725,42.260174,42260.174311,-42217.914137
2451,2452,2024-02-22,3,9,3.0,24.478428,7343.528517,73.435285,7270.093232
2509,2510,2024-02-23,5,18,1000.0,38.425670,38.425670,38425.670452,-38387.244782
2522,2523,2024-02-24,1,3,2.0,15.937370,3187.474100,31.874741,3155.599359
2649,2650,2024-02-26,4,19,3.0,44.818825,13445.647587,134.456476,13311.191111
2727,2728,2024-02-28,2,20,1000.0,28.885567,28.885567,28885.567184,-28856.681617
2761,2762,2024-02-29,1,18,2000.0,17.389756,34.779511,34779.511029,-34744.731518

In [42]:
### Test the two clear scaling patterns before correcting any values.

quantity_scale_error = (
    sales_df["qty"].isin([1000, 2000, 3000, 4000])
    & np.isclose(
        (sales_df["qty"] / 1000) * sales_df["unit_price"],
        sales_df["line_amount"],
        rtol=1e-9,
        atol=0.01
    )
)

line_amount_scale_error = np.isclose(
    sales_df["line_amount"],
    expected_line_amount * 100,
    rtol=1e-9,
    atol=0.01
)

pd.Series({
    "all_calculation_errors": len(calculation_errors),
    "qty_values_multiplied_by_1000": int(quantity_scale_error.sum()),
    "line_amount_values_multiplied_by_100": int(line_amount_scale_error.sum())
})

all_calculation_errors                  43
qty_values_multiplied_by_1000           29
line_amount_values_multiplied_by_100    14
dtype: int64

<div style="background-color:#f3e8ff; padding:12px; border-left:5px solid #8b5cf6; border-radius:6px;">
<h3 style="margin:0;">Calculation Error Investigation</h3>
<p style="margin-bottom:0;">
All 43 calculation errors follow one of two consistent patterns. 29 quantities are 1,000 times too large while the recorded line amount matches qty / 1000 * unit_price. The other 14 rows have sensible quantities and prices but line amounts that are exactly 100 times too large. This provides enough evidence to correct the affected field in each group.
</p>
</div>

In [43]:
### Correct only the rows that match the confirmed scaling patterns.

sales_df["qty_was_corrected"] = False
sales_df["line_amount_was_corrected"] = False

qty_corrections_made = int(quantity_scale_error.sum())
sales_df.loc[quantity_scale_error, "qty"] = (
    sales_df.loc[quantity_scale_error, "qty"] / 1000
)
sales_df.loc[quantity_scale_error, "qty_was_corrected"] = True

expected_after_qty_fix = sales_df["qty"] * sales_df["unit_price"]
line_amount_corrections_made = int(line_amount_scale_error.sum())
sales_df.loc[line_amount_scale_error, "line_amount"] = (
    expected_after_qty_fix[line_amount_scale_error]
)
sales_df.loc[line_amount_scale_error, "line_amount_was_corrected"] = True

In [44]:
### Confirm every sales calculation now matches within one penny.

calculation_errors_remaining = int((
    ~np.isclose(
        sales_df["line_amount"],
        sales_df["qty"] * sales_df["unit_price"],
        rtol=1e-9,
        atol=0.01
    )
).sum())

pd.Series({
    "qty_corrections_made": qty_corrections_made,
    "line_amount_corrections_made": line_amount_corrections_made,
    "calculation_errors_remaining": calculation_errors_remaining
})

qty_corrections_made            29
line_amount_corrections_made    14
calculation_errors_remaining     0
dtype: int64

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Sales Calculation Errors Resolved</h3>
<p style="margin-bottom:0;">
29 quantity values were divided by 1,000 and 14 line amount values were divided by 100 using the confirmed calculation patterns. Every remaining row now satisfies line_amount = qty * unit_price within one penny.
</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Store and Product Referential Integrity</h3>
</div>

In [45]:
### Flag IDs that do not exist in the Stores and Products tables.

sales_df["store_id_was_invalid"] = (
    ~sales_df["store_id"].isin(stores_df["store_id"])
)
sales_df["product_id_was_invalid"] = (
    ~sales_df["product_id"].isin(products_df["product_id"])
)

invalid_store_rows_original = int(sales_df["store_id_was_invalid"].sum())
invalid_product_rows_original = int(sales_df["product_id_was_invalid"].sum())

pd.Series({
    "invalid_store_rows": invalid_store_rows_original,
    "invalid_product_rows": invalid_product_rows_original
})

invalid_store_rows      14
invalid_product_rows    29
dtype: int64

In [46]:
### Review every invalid ID before deciding whether it can be recovered.

invalid_store_rows = sales_df[sales_df["store_id_was_invalid"]]
invalid_product_rows = sales_df[sales_df["product_id_was_invalid"]]

display(invalid_store_rows)
display(invalid_product_rows)

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,qty_was_missing,unit_price_was_missing,qty_was_corrected,line_amount_was_corrected,store_id_was_invalid,product_id_was_invalid
71,72,2024-01-02,9999,9,4.0,36.184603,144.738410,False,False,False,False,True,False
132,133,2024-01-03,9999,3,1.0,48.137147,48.137147,False,False,False,False,True,False
406,407,2024-01-09,9999,16,2.0,49.067686,98.135373,False,False,False,False,True,False
807,808,2024-01-18,9999,20,1.0,49.023042,49.023042,False,False,False,False,True,False
1077,1078,2024-01-23,9999,17,3.0,29.996793,89.990379,False,False,False,False,True,False
1372,1373,2024-01-30,9999,16,1.0,29.888724,29.888724,False,False,False,False,True,False
1686,1687,2024-02-06,9999,20,2.0,4.159847,8.319695,False,False,False,False,True,False
1692,1693,2024-02-06,9999,4,4.0,25.644752,102.579009,False,False,False,False,True,False
1851,1852,2024-02-09,9999,15,4.0,14.217946,56.871784,False,False,False,False,True,False
2002,2003,2024-02-13,9999,2,1.0,47.027079,47.027079,False,False,False,False,True,False
2016,2017,2024-02-13,9999,1,3.0,4.675561,14.026683,False,False,False,False,True,False
2105,2106,2024-02-15,9999,18,1.0,29.403539,29.403539,False,False,False,False,True,False
2427,2428,2024-02-21,9999,9,3.0,42.875907,128.627722,False,True,False,False,True,False
2601,2602,2024-02-25,9999,11,4.0,26.042077,104.168308,False,False,False,False,True,False

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,qty_was_missing,unit_price_was_missing,qty_was_corrected,line_amount_was_corrected,store_id_was_invalid,product_id_was_invalid
44,45,2024-01-01,5,9999,2.0,26.128593,52.257186,False,False,False,False,False,True
57,58,2024-01-02,2,9999,4.0,37.290374,149.161495,True,False,False,False,False,True
70,71,2024-01-02,4,9999,2.0,23.524359,47.048718,False,False,False,False,False,True
111,112,2024-01-03,3,9999,2.0,48.207124,96.414248,False,False,False,False,False,True
120,121,2024-01-03,4,9999,2.0,43.062108,86.124216,False,False,False,False,False,True
178,179,2024-01-04,5,9999,2.0,46.382880,92.765760,False,False,False,False,False,True
332,333,2024-01-07,5,9999,4.0,12.781032,51.124126,False,False,False,False,False,True
410,411,2024-01-09,3,9999,2.0,7.785084,15.570168,False,False,False,False,False,True
516,517,NaT,4,9999,1.0,38.338845,38.338845,False,False,False,False,False,True
567,568,2024-01-12,5,9999,1.0,13.938285,13.938285,False,False,False,False,False,True
580,581,2024-01-13,1,9999,2.0,47.686966,95.373931,False,False,False,False,False,True
590,591,2024-01-13,2,9999,1.0,41.882105,41.882105,False,False,False,False,False,True
594,595,2024-01-13,3,9999,1.0,29.704891,29.704891,False,False,False,False,False,True
1397,1398,2024-01-30,4,9999,1.0,44.200917,44.200917,False,False,False,False,False,True
1398,1399,2024-01-30,4,9999,3.0,28.752184,86.256552,False,False,False,False,False,True
1542,1543,2024-02-03,1,9999,1.0,38.056503,38.056503,False,False,False,False,False,True
1622,1623,2024-02-05,1,9999,1.0,12.688452,12.688452,False,False,False,False,False,True
1704,1705,2024-02-06,5,9999,3.0,5.920029,17.760088,False,False,False,False,False,True
1731,1732,2024-02-07,4,9999,2.0,6.440021,12.880042,False,False,False,False,False,True
1761,1762,2024-02-08,2,9999,3.0,33.665133,100.995399,False,False,False,False,False,True
1816,1817,2024-02-09,2,9999,4.0,7.917621,31.670486,False,False,False,False,False,True
1892,1893,2024-02-10,5,9999,2.0,29.602908,59.205815,False,False,False,False,False,True
2160,2161,2024-02-16,3,9999,2.0,44.448485,88.896969,False,False,False,False,False,True
2269,2270,2024-02-18,3,9999,1.0,7.011938,7.011938,False,False,False,False,False,True
2445,2446,2024-02-22,2,9999,3.0,12.450795,37.352385,False,False,False,False,False,True
2470,2471,2024-02-22,5,9999,1.0,31.882256,31.882256,True,False,False,False,False,True
2481,2482,2024-02-23,1,9999,2.0,21.183584,42.367168,False,False,False,False,False,True
2653,2654,2024-02-26,4,9999,4.0,38.007720,152.030880,False,False,False,False,False,True
2815,1293,2024-01-28,3,9999,3.0,42.247608,126.742824,False,False,False,False,False,True

In [47]:
### Recover the two invalid IDs supported by a matching duplicate transaction.

sales_df["store_id_was_repaired"] = False
sales_df["product_id_was_repaired"] = False

valid_store_for_407 = sales_df.loc[
    (sales_df["txn_id"] == 407)
    & sales_df["store_id"].isin(stores_df["store_id"]),
    "store_id"
].iloc[0]

store_repair_mask = (
    (sales_df["txn_id"] == 407)
    & ~sales_df["store_id"].isin(stores_df["store_id"])
)
sales_df.loc[store_repair_mask, "store_id"] = valid_store_for_407
sales_df.loc[sales_df["txn_id"] == 407, "store_id_was_repaired"] = True

valid_product_for_1293 = sales_df.loc[
    (sales_df["txn_id"] == 1293)
    & sales_df["product_id"].isin(products_df["product_id"]),
    "product_id"
].iloc[0]

product_repair_mask = (
    (sales_df["txn_id"] == 1293)
    & ~sales_df["product_id"].isin(products_df["product_id"])
)
sales_df.loc[product_repair_mask, "product_id"] = valid_product_for_1293
sales_df.loc[sales_df["txn_id"] == 1293, "product_id_was_repaired"] = True

store_ids_repaired = int(store_repair_mask.sum())
product_ids_repaired = int(product_repair_mask.sum())

pd.Series({
    "store_ids_repaired": store_ids_repaired,
    "product_ids_repaired": product_ids_repaired
})

store_ids_repaired      1
product_ids_repaired    1
dtype: int64

In [48]:
### Keep all other invalid IDs unchanged because there is no reliable replacement.

unresolved_store_rows = sales_df[
    ~sales_df["store_id"].isin(stores_df["store_id"])
]
unresolved_product_rows = sales_df[
    ~sales_df["product_id"].isin(products_df["product_id"])
]

print("Unresolved store IDs:", len(unresolved_store_rows))
display(unresolved_store_rows)

print("Unresolved product IDs:", len(unresolved_product_rows))
display(unresolved_product_rows)

Unresolved store IDs: 13

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,qty_was_missing,unit_price_was_missing,qty_was_corrected,line_amount_was_corrected,store_id_was_invalid,product_id_was_invalid,store_id_was_repaired,product_id_was_repaired
71,72,2024-01-02,9999,9,4.0,36.184603,144.738410,False,False,False,False,True,False,False,False
132,133,2024-01-03,9999,3,1.0,48.137147,48.137147,False,False,False,False,True,False,False,False
807,808,2024-01-18,9999,20,1.0,49.023042,49.023042,False,False,False,False,True,False,False,False
1077,1078,2024-01-23,9999,17,3.0,29.996793,89.990379,False,False,False,False,True,False,False,False
1372,1373,2024-01-30,9999,16,1.0,29.888724,29.888724,False,False,False,False,True,False,False,False
1686,1687,2024-02-06,9999,20,2.0,4.159847,8.319695,False,False,False,False,True,False,False,False
1692,1693,2024-02-06,9999,4,4.0,25.644752,102.579009,False,False,False,False,True,False,False,False
1851,1852,2024-02-09,9999,15,4.0,14.217946,56.871784,False,False,False,False,True,False,False,False
2002,2003,2024-02-13,9999,2,1.0,47.027079,47.027079,False,False,False,False,True,False,False,False
2016,2017,2024-02-13,9999,1,3.0,4.675561,14.026683,False,False,False,False,True,False,False,False
2105,2106,2024-02-15,9999,18,1.0,29.403539,29.403539,False,False,False,False,True,False,False,False
2427,2428,2024-02-21,9999,9,3.0,42.875907,128.627722,False,True,False,False,True,False,False,False
2601,2602,2024-02-25,9999,11,4.0,26.042077,104.168308,False,False,False,False,True,False,False,False

Unresolved product IDs: 28

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,qty_was_missing,unit_price_was_missing,qty_was_corrected,line_amount_was_corrected,store_id_was_invalid,product_id_was_invalid,store_id_was_repaired,product_id_was_repaired
44,45,2024-01-01,5,9999,2.0,26.128593,52.257186,False,False,False,False,False,True,False,False
57,58,2024-01-02,2,9999,4.0,37.290374,149.161495,True,False,False,False,False,True,False,False
70,71,2024-01-02,4,9999,2.0,23.524359,47.048718,False,False,False,False,False,True,False,False
111,112,2024-01-03,3,9999,2.0,48.207124,96.414248,False,False,False,False,False,True,False,False
120,121,2024-01-03,4,9999,2.0,43.062108,86.124216,False,False,False,False,False,True,False,False
178,179,2024-01-04,5,9999,2.0,46.382880,92.765760,False,False,False,False,False,True,False,False
332,333,2024-01-07,5,9999,4.0,12.781032,51.124126,False,False,False,False,False,True,False,False
410,411,2024-01-09,3,9999,2.0,7.785084,15.570168,False,False,False,False,False,True,False,False
516,517,NaT,4,9999,1.0,38.338845,38.338845,False,False,False,False,False,True,False,False
567,568,2024-01-12,5,9999,1.0,13.938285,13.938285,False,False,False,False,False,True,False,False
580,581,2024-01-13,1,9999,2.0,47.686966,95.373931,False,False,False,False,False,True,False,False
590,591,2024-01-13,2,9999,1.0,41.882105,41.882105,False,False,False,False,False,True,False,False
594,595,2024-01-13,3,9999,1.0,29.704891,29.704891,False,False,False,False,False,True,False,False
1397,1398,2024-01-30,4,9999,1.0,44.200917,44.200917,False,False,False,False,False,True,False,False
1398,1399,2024-01-30,4,9999,3.0,28.752184,86.256552,False,False,False,False,False,True,False,False
1542,1543,2024-02-03,1,9999,1.0,38.056503,38.056503,False,False,False,False,False,True,False,False
1622,1623,2024-02-05,1,9999,1.0,12.688452,12.688452,False,False,False,False,False,True,False,False
1704,1705,2024-02-06,5,9999,3.0,5.920029,17.760088,False,False,False,False,False,True,False,False
1731,1732,2024-02-07,4,9999,2.0,6.440021,12.880042,False,False,False,False,False,True,False,False
1761,1762,2024-02-08,2,9999,3.0,33.665133,100.995399,False,False,False,False,False,True,False,False
1816,1817,2024-02-09,2,9999,4.0,7.917621,31.670486,False,False,False,False,False,True,False,False
1892,1893,2024-02-10,5,9999,2.0,29.602908,59.205815,False,False,False,False,False,True,False,False
2160,2161,2024-02-16,3,9999,2.0,44.448485,88.896969,False,False,False,False,False,True,False,False
2269,2270,2024-02-18,3,9999,1.0,7.011938,7.011938,False,False,False,False,False,True,False,False
2445,2446,2024-02-22,2,9999,3.0,12.450795,37.352385,False,False,False,False,False,True,False,False
2470,2471,2024-02-22,5,9999,1.0,31.882256,31.882256,True,False,False,False,False,True,False,False
2481,2482,2024-02-23,1,9999,2.0,21.183584,42.367168,False,False,False,False,False,True,False,False
2653,2654,2024-02-26,4,9999,4.0,38.007720,152.030880,False,False,False,False,False,True,False,False

<div style="background-color:#fff7ed; padding:12px; border-left:5px solid #f97316; border-radius:6px;">
<h3 style="margin:0;">Unresolved Invalid IDs Retained</h3>
<p style="margin-bottom:0;">
One invalid store ID and one invalid product ID were recovered from matching records with the same transaction ID. The remaining 13 store IDs and 28 product IDs use 9999, but no other field provides a reliable replacement. They have been retained and flagged rather than guessed or deleted.
</p>
</div>

In [49]:
### Preserve repair evidence, then remove the three records that are now confirmed duplicates.

repair_flags = [
    "qty_was_corrected",
    "line_amount_was_corrected",
    "store_id_was_repaired",
    "product_id_was_repaired"
]

for flag in repair_flags:
    sales_df[flag] = (
        sales_df.groupby("txn_id")[flag]
        .transform("max")
        .astype(bool)
    )

repaired_duplicates_removed = int(
    sales_df.duplicated(subset=sales_columns).sum()
)

sales_df = sales_df.drop_duplicates(
    subset=sales_columns
).copy()

pd.Series({
    "additional_exact_duplicates_removed": repaired_duplicates_removed,
    "duplicate_transaction_ids_remaining": sales_df["txn_id"].duplicated().sum(),
    "rows_remaining": len(sales_df)
})

additional_exact_duplicates_removed       3
duplicate_transaction_ids_remaining       0
rows_remaining                         2809
dtype: int64

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Duplicate Transaction IDs Resolved</h3>
<p style="margin-bottom:0;">
After the evidence-based repairs, the remaining three duplicate transaction pairs became exact matches. Their additional copies were removed and txn_id is now unique.
</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Missing Transaction Dates</h3>
</div>

In [50]:
### Compare each missing date with the previous and next transaction dates.

sales_df["txn_date_was_missing"] = sales_df["txn_date"].isnull()

sales_sorted = sales_df.sort_values("txn_id").copy()
sales_sorted["previous_date"] = sales_sorted["txn_date"].shift(1)
sales_sorted["next_date"] = sales_sorted["txn_date"].shift(-1)

missing_date_review = sales_sorted[
    sales_sorted["txn_date"].isnull()
][
    ["txn_id", "previous_date", "txn_date", "next_date"]
].copy()

missing_date_review["safe_to_repair"] = (
    missing_date_review["previous_date"].notnull()
    & missing_date_review["previous_date"].eq(
        missing_date_review["next_date"]
    )
)

missing_date_review

      txn_id previous_date txn_date  next_date  safe_to_repair
177      178    2024-01-04      NaT 2024-01-04            True
212      213    2024-01-05      NaT 2024-01-05            True
237      238    2024-01-05      NaT 2024-01-05            True
263      264    2024-01-06      NaT 2024-01-06            True
277      278    2024-01-06      NaT 2024-01-06            True
310      311    2024-01-07      NaT 2024-01-07            True
366      367    2024-01-08      NaT 2024-01-08            True
516      517    2024-01-11      NaT 2024-01-11            True
640      641    2024-01-14      NaT 2024-01-14            True
672      673    2024-01-15      NaT 2024-01-15            True
816      817    2024-01-18      NaT 2024-01-18            True
889      890    2024-01-19      NaT 2024-01-19            True
906      907    2024-01-20      NaT 2024-01-20            True
977      978    2024-01-21      NaT 2024-01-21            True
1079    1080    2024-01-23      NaT 2024-01-23            True
1186    1187    2024-01-26      NaT 2024-01-26            True
1368    1369    2024-01-30      NaT 2024-01-30            True
1518    1519    2024-02-02      NaT 2024-02-02            True
1522    1523    2024-02-02      NaT 2024-02-02            True
1705    1706    2024-02-06      NaT 2024-02-06            True
1730    1731    2024-02-07      NaT 2024-02-07            True
1765    1766    2024-02-08      NaT 2024-02-08            True
2043    2044    2024-02-14      NaT 2024-02-14            True
2049    2050    2024-02-14      NaT 2024-02-14            True
2079    2080    2024-02-14      NaT 2024-02-14            True
2099    2100    2024-02-15      NaT 2024-02-15            True
2242    2243    2024-02-17      NaT 2024-02-17            True
2384    2385    2024-02-20      NaT 2024-02-20            True
2768    2769    2024-02-29      NaT 2024-02-29            True

In [51]:
### Fill only dates where the previous and next transaction dates agree.

safe_dates = missing_date_review[
    missing_date_review["safe_to_repair"]
].set_index("txn_id")["previous_date"]

date_repair_mask = (
    sales_df["txn_date"].isnull()
    & sales_df["txn_id"].isin(safe_dates.index)
)

txn_dates_repaired = int(date_repair_mask.sum())

sales_df.loc[date_repair_mask, "txn_date"] = (
    sales_df.loc[date_repair_mask, "txn_id"]
    .map(safe_dates)
)

pd.Series({
    "transaction_dates_repaired": txn_dates_repaired,
    "missing_dates_remaining": sales_df["txn_date"].isnull().sum()
})

transaction_dates_repaired    29
missing_dates_remaining        0
dtype: int64

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Missing Transaction Dates Resolved</h3>
<p style="margin-bottom:0;">
All 29 missing dates occurred between transactions with the same date. Only those matching neighbour dates were used, so no date was filled using a blind forward or backward fill.
</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Quantity and Unit Price Validation</h3>
</div>

In [52]:
### Confirm quantities are positive whole numbers, then use an integer data type.

sales_df["qty"] = sales_df["qty"].astype("int64")

pd.Series({
    "minimum_qty": sales_df["qty"].min(),
    "maximum_qty": sales_df["qty"].max(),
    "zero_or_negative_qty_rows": (sales_df["qty"] <= 0).sum(),
    "non_whole_qty_rows": (sales_df["qty"] % 1 != 0).sum(),
    "qty_data_type": str(sales_df["qty"].dtype)
})

minimum_qty                      1
maximum_qty                      4
zero_or_negative_qty_rows        0
non_whole_qty_rows               0
qty_data_type                int64
dtype: object

In [53]:
### Confirm unit prices are positive and review their range.

print(sales_df["unit_price"].describe())

pd.Series({
    "zero_or_negative_unit_price_rows": (sales_df["unit_price"] <= 0).sum(),
    "minimum_unit_price": sales_df["unit_price"].min(),
    "maximum_unit_price": sales_df["unit_price"].max()
})

count    2809.000000
mean       26.045727
std        13.933636
min         2.001475
25%        14.085550
50%        26.096393
75%        38.231718
max        49.986448
Name: unit_price, dtype: float64

zero_or_negative_unit_price_rows     0.000000
minimum_unit_price                   2.001475
maximum_unit_price                  49.986448
dtype: float64

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Quantity and Unit Price Values Validated</h3>
<p style="margin-bottom:0;">
All quantities are positive whole numbers between 1 and 4 and are stored as integers. All unit prices are positive and remain within the established dataset range of approximately 2.00 to 49.99.
</p>
</div>

<div style="background-color:#e8f1ff; padding:12px; border-left:5px solid #4a90e2; border-radius:6px;">
<h3 style="margin:0;">Final Sales Data Validation</h3>
</div>

In [54]:
### Run the final validation checks in one summary.

final_calculation_errors = int((
    ~np.isclose(
        sales_df["line_amount"],
        sales_df["qty"] * sales_df["unit_price"],
        rtol=1e-9,
        atol=0.01
    )
).sum())

unresolved_store_count = int((
    ~sales_df["store_id"].isin(stores_df["store_id"])
).sum())
unresolved_product_count = int((
    ~sales_df["product_id"].isin(products_df["product_id"])
).sum())

final_validation = pd.Series({
    "final_row_count": len(sales_df),
    "null_values_in_business_columns": sales_df[sales_columns].isnull().sum().sum(),
    "exact_duplicate_rows": sales_df.duplicated(subset=sales_columns).sum(),
    "duplicate_transaction_ids": sales_df["txn_id"].duplicated().sum(),
    "calculation_errors": final_calculation_errors,
    "zero_or_negative_quantities": (sales_df["qty"] <= 0).sum(),
    "non_whole_quantities": (sales_df["qty"] % 1 != 0).sum(),
    "zero_or_negative_unit_prices": (sales_df["unit_price"] <= 0).sum(),
    "unresolved_store_ids": unresolved_store_count,
    "unresolved_product_ids": unresolved_product_count
})

final_validation

final_row_count                    2809
null_values_in_business_columns       0
exact_duplicate_rows                  0
duplicate_transaction_ids             0
calculation_errors                    0
zero_or_negative_quantities           0
non_whole_quantities                  0
zero_or_negative_unit_prices          0
unresolved_store_ids                 13
unresolved_product_ids               28
dtype: int64

In [55]:
### Summarise the issues that remain unresolved and require source data.

unresolved_issues = pd.DataFrame({
    "issue": [
        "store_id does not exist in stores_df",
        "product_id does not exist in products_df"
    ],
    "rows": [
        unresolved_store_count,
        unresolved_product_count
    ],
    "action": [
        "Retained and flagged; correct store cannot be safely inferred",
        "Retained and flagged; correct product cannot be safely inferred"
    ]
})

unresolved_issues

,issue,rows,action
0,store_id does not exist in stores_df,13,Retained and flagged; correct store cannot be ...
1,product_id does not exist in products_df,28,Retained and flagged; correct product cannot b...

In [56]:
### Record the changes made during the Sales cleaning workflow.

audit_summary = pd.Series({
    "rows_loaded": rows_original,
    "missing_qty_values_reconstructed": qty_values_reconstructed,
    "missing_unit_prices_reconstructed": unit_price_values_reconstructed,
    "initial_exact_duplicates_removed": exact_duplicates_removed,
    "additional_duplicates_removed_after_repairs": repaired_duplicates_removed,
    "qty_values_corrected": qty_corrections_made,
    "line_amount_values_corrected": line_amount_corrections_made,
    "store_ids_recovered": store_ids_repaired,
    "product_ids_recovered": product_ids_repaired,
    "transaction_dates_repaired": txn_dates_repaired,
    "final_rows": len(sales_df),
    "unresolved_store_ids": unresolved_store_count,
    "unresolved_product_ids": unresolved_product_count
})

audit_summary

rows_loaded                                    2859
missing_qty_values_reconstructed                 57
missing_unit_prices_reconstructed                56
initial_exact_duplicates_removed                 47
additional_duplicates_removed_after_repairs       3
qty_values_corrected                             29
line_amount_values_corrected                     14
store_ids_recovered                               1
product_ids_recovered                             1
transaction_dates_repaired                       29
final_rows                                     2809
unresolved_store_ids                             13
unresolved_product_ids                           28
dtype: int64

In [57]:
### Confirm final data types and review the cleaned Sales table.

print(sales_df.dtypes)
sales_df.head()

txn_id                                int64
txn_date                     datetime64[us]
store_id                              int64
product_id                            int64
qty                                   int64
unit_price                          float64
line_amount                         float64
qty_was_missing                        bool
unit_price_was_missing                 bool
qty_was_corrected                      bool
line_amount_was_corrected              bool
store_id_was_invalid                   bool
product_id_was_invalid                 bool
store_id_was_repaired                  bool
product_id_was_repaired                bool
txn_date_was_missing                   bool
dtype: object

,txn_id,txn_date,store_id,product_id,qty,unit_price,line_amount,qty_was_missing,unit_price_was_missing,qty_was_corrected,line_amount_was_corrected,store_id_was_invalid,product_id_was_invalid,store_id_was_repaired,product_id_was_repaired,txn_date_was_missing
0,1,2024-01-01,1,2,4,13.569222,54.276889,False,False,False,False,False,False,False,False,False
1,2,2024-01-01,1,7,4,25.768492,103.073967,False,False,False,False,False,False,False,False,False
2,3,2024-01-01,1,15,3,45.647379,136.942138,False,False,False,False,False,False,False,False,False
3,4,2024-01-01,1,4,2,33.801070,67.602139,False,False,False,False,False,False,False,False,False
4,5,2024-01-01,1,2,2,26.963265,53.926530,False,False,False,False,False,False,False,False,False

<div style="background-color:#ecfdf3; padding:12px; border-left:5px solid #16a34a; border-radius:6px;">
<h3 style="margin:0;">Sales Cleaning Workflow Complete</h3>
<p style="margin-bottom:0;">
All safely repairable missing values, duplicates and calculation errors have been resolved. Transaction IDs are unique, quantities and prices are valid, and every line amount matches qty * unit_price. The remaining 9999 store and product IDs cannot be recovered from the available data, so they have been retained, flagged and documented for follow-up with the source system.
</p>
</div>